# Support StackShift Development

<<<<<<< HEAD
github: jschulte
ko_fi: jschulte
=======
# Primary funding (once Ko-fi is set up)
ko_fi: YOUR_KOFI_USERNAME  # Replace with your Ko-fi username

# Future: GitHub Sponsors (once approved)
# github: jschulte

# Optional: Add custom link
custom: ["https://github.com/jschulte/stackshift"]
>>>>>>> fe2d2e9e8ad0a4b341e45114c9ae94056fae273e
